"""
SCARLI-MUSIC — localization
EN / UA / SU (Soviet)
"""

LANG = {
    "en": {
        "no_track":    "NO TRACK",
        "stopped":     "STOPPED",
        "playing":     "PLAYING",
        "paused":      "PAUSED",
        "ready":       "READY",
        "open":        "OPEN",
        "play":        "PLAY",
        "pause":       "PAUSE",
        "stop":        "STOP",
        "resume":      "RESUME",
        "volume":      "VOLUME",
        "speed":       "SPEED",
        "tape":        "TAPE POSITION",
        "playlist":    "PLAYLIST",
        "fav":         "FAV",
        "next":        "NEXT",
        "prev":        "PREV",
        "coming_soon": "COMING SOON",
        "favorite":    "FAVORITE",
        "m_file":      "File",
        "m_open":      "Open...",
        "m_exit":      "Exit",
        "m_playlist":  "Playlist",
        "m_show_pl":   "Show playlist",
        "m_add_pl":    "Add current to playlist",
        "m_next":      "Next track",
        "m_prev":      "Previous track",
        "m_theme":     "Theme",
        "m_settings":  "Settings",
        "m_settings_w":"Settings",
        "m_about":     "About",
        "s_title":     "SETTINGS",
        "s_sound":     "SOUND",
        "s_fadein":    "Fade in on play",
        "s_fadeout":   "Fade out on pause",
        "s_fadebet":   "Fade between tracks",
        "s_gapless":   "Gapless playback",
        "s_repeat":    "REPEAT & SHUFFLE",
        "s_repeat_l":  "Repeat:",
        "s_shuffle_l": "Shuffle:",
        "s_visual":    "VISUAL",
        "s_clock":     "Show clock",
        "s_reels":     "Reels animation",
        "s_ticker":    "Scrolling title",
        "s_scan":      "CRT scanlines",
        "s_flicker":   "CRT flicker",
        "s_perf":      "PERFORMANCE",
        "s_eco":       "Eco mode (disable animations)",
        "s_lowq":      "Low-quality render (faster on weak PC)",
        "s_statscr":   "Static scrubber (less CPU)",
        "s_led":       "LED indicators",
        "s_winanim":   "Window open animation",
        "s_theme":     "THEME",
        "s_lang":      "LANGUAGE",
        "s_close":     "CLOSE",
        "p_title":     "PLAYLIST",
        "p_add":       "+ ADD",
        "p_close":     "CLOSE",
        "p_search":    "Search:",
        "p_sort":      "Sort:",
        "p_fav":       "FAVORITE",
        "p_remove":    "REMOVE",
        "p_clear":     "CLEAR",
        "p_export":    "EXPORT .m3u",
        "p_import":    "IMPORT .m3u",
        "d_about":     "About",
        "d_abouttxt":  "Retro player inspired by Soviet radio electronics.\nPython 3.14 + pygame-ce + tkinter\n© 2026 · no hosting, all local",
        "d_error":     "Error",
        "d_notfound":  "File not found:\n",
        "d_loaderr":   "Failed to load:\n",
        "d_clearq":    "Remove all tracks?",
        "d_exp":       "Export",
        "d_imp":       "Import",
        "d_saved":     "Saved: ",
    },
    "ua": {
        "no_track":    "НЕМАЄ ТРЕКУ",
        "stopped":     "ЗУПИНЕНО",
        "playing":     "ГРАЄ",
        "paused":      "ПАУЗА",
        "ready":       "ГОТОВО",
        "open":        "ВІДКРИТИ",
        "play":        "ГРАТИ",
        "pause":       "ПАУЗА",
        "stop":        "СТОП",
        "resume":      "ДАЛІ",
        "volume":      "ГУЧНІСТЬ",
        "speed":       "ШВИДКІСТЬ",
        "tape":        "ПОЗИЦІЯ СТРІЧКИ",
        "playlist":    "ПЛЕЙЛИСТ",
        "fav":         "УЛЮБЛЕНЕ",
        "next":        "ДАЛІ",
        "prev":        "НАЗАД",
        "coming_soon": "СКОРО",
        "favorite":    "В ОБРАНЕ",
        "m_file":      "Файл",
        "m_open":      "Відкрити...",
        "m_exit":      "Вихід",
        "m_playlist":  "Плейлист",
        "m_show_pl":   "Показати плейлист",
        "m_add_pl":    "Додати трек до плейлиста",
        "m_next":      "Наступний трек",
        "m_prev":      "Попередній трек",
        "m_theme":     "Тема",
        "m_settings":  "Налаштування",
        "m_settings_w":"Налаштування",
        "m_about":     "Про програму",
        "s_title":     "НАЛАШТУВАННЯ",
        "s_sound":     "ЗВУК",
        "s_fadein":    "Плавний вхід при відтворенні",
        "s_fadeout":   "Плавне затухання при паузі",
        "s_fadebet":   "Плавний перехід між треками",
        "s_gapless":   "Без пауз між треками",
        "s_repeat":    "ПОВТОР І ПЕРЕМІШУВАННЯ",
        "s_repeat_l":  "Повтор:",
        "s_shuffle_l": "Перемішування:",
        "s_visual":    "ВИГЛЯД",
        "s_clock":     "Показувати годинник",
        "s_reels":     "Анімація котушок",
        "s_ticker":    "Рядок, що біжить",
        "s_scan":      "Рядки CRT",
        "s_flicker":   "Мерехтіння CRT",
        "s_perf":      "ПРОДУКТИВНІСТЬ",
        "s_eco":       "Економний режим (вимкнути анімації)",
        "s_lowq":      "Низька якість рендеру (швидше на слабких ПК)",
        "s_statscr":   "Статичний скраббер (менше CPU)",
        "s_led":       "LED-індикатори",
        "s_winanim":   "Анімація відкриття вікна",
        "s_theme":     "ТЕМА",
        "s_lang":      "МОВА",
        "s_close":     "ЗАКРИТИ",
        "p_title":     "ПЛЕЙЛИСТ",
        "p_add":       "+ ДОДАТИ",
        "p_close":     "ЗАКРИТИ",
        "p_search":    "Пошук:",
        "p_sort":      "Сортування:",
        "p_fav":       "В ОБРАНЕ",
        "p_remove":    "ВИДАЛИТИ",
        "p_clear":     "ОЧИСТИТИ",
        "p_export":    "ЕКСПОРТ .m3u",
        "p_import":    "ІМПОРТ .m3u",
        "d_about":     "Про програму",
        "d_abouttxt":  "Ретро-плеєр у стилі радянської радіоелектроніки.\nPython 3.14 + pygame-ce + tkinter\n© 2026 · без хостингу, все локально",
        "d_error":     "Помилка",
        "d_notfound":  "Файл не знайдено:\n",
        "d_loaderr":   "Не вдалося завантажити:\n",
        "d_clearq":    "Видалити всі треки?",
        "d_exp":       "Експорт",
        "d_imp":       "Імпорт",
        "d_saved":     "Збережено: ",
    },
    "su": {
        "no_track":    "НЕТ ПЛЁНКИ",
        "stopped":     "ОСТАНОВЛЕНО",
        "playing":     "ВОСПРОИЗВЕДЕНИЕ",
        "paused":      "ПАУЗА",
        "ready":       "ГОТОВ К РАБОТЕ",
        "open":        "ОТКРЫТЬ",
        "play":        "ПУСК",
        "pause":       "ПАУЗА",
        "stop":        "СТОП",
        "resume":      "ПРОДОЛЖИТЬ",
        "volume":      "ГРОМКОСТЬ",
        "speed":       "СКОРОСТЬ",
        "tape":        "ПОЛОЖЕНИЕ ЛЕНТЫ",
        "playlist":    "ФОНОТЕКА",
        "fav":         "ИЗБРАННОЕ",
        "next":        "ДАЛЕЕ",
        "prev":        "НАЗАД",
        "coming_soon": "В РАЗРАБОТКЕ",
        "favorite":    "В ИЗБРАННОМ",
        "m_file":      "Файл",
        "m_open":      "Открыть...",
        "m_exit":      "Выход",
        "m_playlist":  "Фонотека",
        "m_show_pl":   "Показать фонотеку",
        "m_add_pl":    "Занести в фонотеку",
        "m_next":      "Следующая запись",
        "m_prev":      "Предыдущая запись",
        "m_theme":     "Оформление",
        "m_settings":  "Настройки",
        "m_settings_w":"Настройки",
        "m_about":     "О программе",
        "s_title":     "НАСТРОЙКИ",
        "s_sound":     "ЗВУК",
        "s_fadein":    "Плавное начало воспроизведения",
        "s_fadeout":   "Плавное затухание при паузе",
        "s_fadebet":   "Плавный переход между записями",
        "s_gapless":   "Без пауз между записями",
        "s_repeat":    "ПОВТОР И ПЕРЕМЕШИВАНИЕ",
        "s_repeat_l":  "Повтор:",
        "s_shuffle_l": "Перемешивание:",
        "s_visual":    "ОФОРМЛЕНИЕ",
        "s_clock":     "Показывать часы",
        "s_reels":     "Вращение катушек",
        "s_ticker":    "Бегущая строка",
        "s_scan":      "Развёртка ЭЛТ",
        "s_flicker":   "Мерцание ЭЛТ",
        "s_perf":      "ПРОИЗВОДИТЕЛЬНОСТЬ",
        "s_eco":       "Экономный режим (отключить анимации)",
        "s_lowq":      "Пониженное качество отрисовки (для слабых ЭВМ)",
        "s_statscr":   "Статичная шкала (меньше нагрузка на ЦП)",
        "s_led":       "Светодиодные индикаторы",
        "s_winanim":   "Анимация открытия окна",
        "s_theme":     "ОФОРМЛЕНИЕ",
        "s_lang":      "ЯЗЫК",
        "s_close":     "ЗАКРЫТЬ",
        "p_title":     "ФОНОТЕКА",
        "p_add":       "+ ДОБАВИТЬ",
        "p_close":     "ЗАКРЫТЬ",
        "p_search":    "Поиск:",
        "p_sort":      "Сортировка:",
        "p_fav":       "В ИЗБРАННОЕ",
        "p_remove":    "УДАЛИТЬ",
        "p_clear":     "ОЧИСТИТЬ",
        "p_export":    "ЭКСПОРТ .m3u",
        "p_import":    "ИМПОРТ .m3u",
        "d_about":     "О программе",
        "d_abouttxt":  "Ретро-плеер в духе советской радиоэлектроники.\nPython 3.14 + pygame-ce + tkinter\n© 2026 · без хостинга, всё локально",
        "d_error":     "Ошибка",
        "d_notfound":  "Файл не найден:\n",
        "d_loaderr":   "Не удалось загрузить:\n",
        "d_clearq":    "Удалить все записи?",
        "d_exp":       "Экспорт",
        "d_imp":       "Импорт",
        "d_saved":     "Сохранено: ",
    },
}

_current_lang = "en"


def set_lang(code: str) -> None:
    global _current_lang
    _current_lang = code if code in LANG else "en"


def t(key: str) -> str:
    """Возвращает перевод по ключу. Fallback: EN."""
    return LANG.get(_current_lang, LANG["en"]).get(
        key, LANG["en"].get(key, key)
    )


def current_lang() -> str:
    return _current_lang


def lang_display_name(code: str) -> str:
    return {"en": "ENGLISH", "ua": "УКРАЇНСЬКА", "su": "СОВЕТСКИЙ"}.get(code, code.upper())